//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  #[sea_orm(unique)]
  pub email: String,
  pub avatar_url: String,
  pub refresh_token_hash: Option<String>,
  pub last_login: Option<DateTime>,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::user_permission::Entity")]
  UserPermission,
}

impl Related<super::user_permission::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserPermission.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
