[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
api = { path = "../api" }
config = { path = "../config" }
database = { path = "../database" }
adapters = { path = "../adapters" }
actix-web = { workspace = true }
reqwest = { workspace = true }
