[env]

# RUST_BACKTRACE = "1"
RUST_LOG = "server=debug,api=debug,api_crud=debug,api_common=debug,routes=debug,database=debug,utils=debug,actix_server=debug,actix_web::middleware::logger=debug,aws_sdk_s3=debug,actix_web::data"
